- name: Harden with Fail2Ban
  hosts: all
  become: yes

  tasks:
    - name: Ensure fail2ban is installed
      ansible.builtin.package:
        name: fail2ban
        state: present

    - name: Deploy jail.local config
      ansible.builtin.copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          bantime  = {{ fail2ban_settings.bantime }}
          findtime  = {{ fail2ban_settings.findtime }}
          maxretry = {{ fail2ban_settings.maxretry }}
          backend = systemd

{% for jail in fail2ban_settings.enabled_jails %}
          [{{ jail.name }}]
          enabled = true
          port    = {{ jail.port }}
          logpath = {{ jail.logpath }}
          backend = {{ jail.backend | default('systemd') }}

{% endfor %}

    - name: Ensure fail2ban service is enabled and running
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: yes

